version: '3.8'

services:
  k8s-backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env   
    networks:
      - app-network

  k8s-frontend:
    build: ./frontend
    container_name: node_frontend
    ports:
      - "3000:3000"
    depends_on:
      - k8s-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge